apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faulty-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-faulty
    server: https://kubernetes.default.svc
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
